package helpers;

import android.content.Context;



public class FillingDB {
	public static void Fill(Context mContext){

	DBAdapter db = new DBAdapter(mContext);
	db.open();

	//Filling the table Patient
	db.insertPatient("cool", "itsworking");
	// Filling the table AnswerContent_translate
	db.InsertAnswerTable(1, "Pas du tout", "Un peu", "Moyennement", "Beaucoup", "Enormément", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(2, "Sans aucune difficulté", "Quelques difficultés", "Beaucoup de difficultés", "Incapable", "NULL","NULL", "NULL", "NULL");
	db.InsertAnswerTable(3, "Aucune douleur", "Faible douleur", "Douleur modérée", "Forte douleur", "NULL", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(4, "Oui", "Non", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(6, "IRM", "Radiographie", "NULL", "NULL", "NULL", "NULL", "NULL","NULL");
	db.InsertAnswerTable(7, "CRP", "VS", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(8, "Fièvre", "Maux de tête", "Troubles digestifs", "Toux", "Signes cutanés", "Aucun", "NULL", "NULL");
	db.InsertAnswerTable(13, "Je suis enceinte", "Pilules contraceptives", "Stérilet", "Autre", "Aucun","NULL", "NULL", "NULL");
	db.InsertAnswerTable(14, "Fumeur", "Hypercholestérolémique", "Diabétique", "Hypertendu", "Autre", "Aucun", "NULL", "NULL");
	db.InsertAnswerTable(15, "Infection urinaire", "La tuberculose", "La sinusite", "La pneumonie", "Aucun", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(16, "Médecin généraliste", "Rhumatologue libéral", "Rhumatologue hospitalier", "Autre", "NULL", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(17, "Femme", "Homme", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(18, "En service", "En retraite", "En chomage", "En invalidite", "Autre", "NULL", "NULL", "NULL");
	db.InsertAnswerTable(19, "Visite médicale", "Consultation infirmière", "Des séances de kinésithérapie", "Radiographie", "Prise de sang", "Aucun", "NULL", "NULL");
	//Filling the table Countries
	db.InsertCountry(1, "FR");
	//Filling the table Drug_Content
	db.InsertDrug_Content(1, "ARA", 2, "Arava", 1, 1);
	db.InsertDrug_Content(2, "COR", 2, "Cortico¨de",1, 1);
	db.InsertDrug_Content(3, "ME", 2, "Méthotrexate", 1,1);
	db.InsertDrug_Content(4, "PL", 2, "Plaquenil", 1, 1);
	db.InsertDrug_Content(5, "SA", 2, "Salazopyrine", 1, 1);
	db.InsertDrug_Content(8, "CI", 1, "Cimzia", 1, 1);
	db.InsertDrug_Content(9, "EN", 1, "Enbrel", 1, 1);
	db.InsertDrug_Content(10, "HU", 1, "Humira", 1, 1);
	db.InsertDrug_Content(11, "IM", 1, "Imurel", 1, 1);
	db.InsertDrug_Content(12, "KI", 1, "Kineret", 1, 1);
	db.InsertDrug_Content(13, "MA", 1, "Mabthera", 1, 1);
	db.InsertDrug_Content(14, "OR", 1, "Orencia", 1, 1);
	db.InsertDrug_Content(15, "ROA", 1, "Roactemra", 1, 1);
	db.InsertDrug_Content(16, "SY", 1, "Symponi", 1, 1);
	db.InsertDrug_Content(17, "RE", 1, "Remicade", 1, 1);
	db.InsertDrug_Content(18, "ANN", 3, "Aparanax/Naproxene/Naprosyne", 1, 1);
	db.InsertDrug_Content(20, "ARC", 3, "Arcoxia", 1, 1);
	db.InsertDrug_Content(21, "BK", 3, "Bi Profenid/Ketoprofene (intra-musculaire) ", 1, 1);
	db.InsertDrug_Content(22, "CEB", 3, "Cebutid", 1, 1);
	db.InsertDrug_Content(24, "CEL", 3, "Célébrex", 1, 1);
	db.InsertDrug_Content(25, "FPBT", 3, "Feldene/Piroxicam/Brexim/Tilcotil", 1, 1);
	db.InsertDrug_Content(26, "VD", 3, "Voltarene/Diclofenac", 1, 1);
	db.InsertDrug_Content(27, "IN", 3, "Indocid", 1, 1);
	db.InsertDrug_Content(28, "CH", 3, "Chrono-Indocid", 1, 1);
	db.InsertDrug_Content(29, "PKc", 3, "Profenid/Ketoprofene (comprimés)", 1, 1);
	db.InsertDrug_Content(30, "PKg", 3, "Profenid/Ketoprofene (gelules)", 1, 1);
	db.InsertDrug_Content(31, "MM", 3, "Mobic/Meloxicam", 1, 1);
	db.InsertDrug_Content(32, "CA", 3, "Cartrex/Aceclofenac", 1, 1);
	db.InsertDrug_Content(33, "AINS", 3, "Advil/Ibuprofene/Nurofene/Spifen", 1, 1);
	db.InsertDrug_Content(34, "GEP", 4, "Geluprane", 1, 1);
	db.InsertDrug_Content(36, "GEF", 4, "Gelufene", 1, 1);
	db.InsertDrug_Content(37, "ACT", 4, "Actifed", 1, 1);
	db.InsertDrug_Content(38, "EF", 4, "Efferalgan", 1, 1);
	db.InsertDrug_Content(39, "ACU", 5, "Acupan", 1, 1);
	db.InsertDrug_Content(40, "CTT", 5, "Contramal/Tramadol/Topalgic", 1, 1);
	db.InsertDrug_Content(41, "DC", 5, "Dafalgan Codeine", 1, 1);
	db.InsertDrug_Content(42, "DPE", 5, "Doliprane/Paracétamol/Efferalgan", 1, 1);
	db.InsertDrug_Content(44, "ECKC", 5, "Efferalgan Codeine/Klipal Codeine", 1, 1);
	db.InsertDrug_Content(45, "IX", 5, "Ixprim/Zaldiar", 1, 1);
	db.InsertDrug_Content(47, "LA", 5, "Lamaline", 1, 1);
	db.InsertDrug_Content(52, "PKim", 3, "Profenid/Ketoprofene (Intra-Musculaire)", 1, 1);
	//Filling the table QuestionContent_translate
	//db.DeleteQuestion(117); 
	//db.DeleteQuestion(118);
	//db.DeleteQuestion(119);
	db.DeleteQuestion(90);
	db.DeleteQuestion(92);
	db.DeleteQuestion(124);
	db.DeleteQuestion(128);
	db.DeleteQuestion(126);
	db.DeleteQuestion(158);
	db.DeleteQuestion(54);
	db.DeleteQuestion(55);
	db.DeleteQuestion(56);
	db.DeleteQuestion(57);
	db.DeleteQuestion(58);
	db.DeleteQuestion(135);
	db.DeleteQuestion(137);
	db.DeleteQuestion(138);
	db.DeleteQuestion(139);
	db.DeleteQuestion(134);
	db.DeleteQuestion(141);
	db.DeleteQuestion(142);
	db.DeleteQuestion(143);
	db.DeleteQuestion(144);
	db.DeleteQuestion(140);
	db.DeleteQuestion(146);
	db.DeleteQuestion(145);
	db.DeleteQuestion(148);
	db.DeleteQuestion(147);
	db.DeleteQuestion(149);
	db.DeleteQuestion(114);
	db.DeleteQuestion(112);
	db.DeleteQuestion(74);
	db.DeleteQuestion(70);
	
	

	db.InsertQuestionContent_translate(1, "Je me sens épuisé(e)", 20, 1, 1);
	db.InsertQuestionContent_translate(3, "Je ressens une faiblesse générale", 21, 1, 1);
	db.InsertQuestionContent_translate(4, "Je suis sans énergie [lessivé(e)]", 22, 1, 1);
	db.InsertQuestionContent_translate(5, "Je me sens fatigué(e)", 23, 1, 1);
	db.InsertQuestionContent_translate(7, "J'ai du mal à commencer les choses parce que je suis fatigué(e)", 24, 1, 1);
	db.InsertQuestionContent_translate(9, "J'ai du mal à terminer les choses parce que je suis fatigué(e)", 25, 1, 1);
	db.InsertQuestionContent_translate(10, "J'ai de l'énergie", 26, 1, 1);
	db.InsertQuestionContent_translate(11, "Je suis capable de faire ce que je fais d'habitude", 27, 1, 1);
	db.InsertQuestionContent_translate(12, "J'ai besoin de dormir dans la journée", 28, 1, 1);
	db.InsertQuestionContent_translate(13, "Je suis trop fatigué(e) pour manger", 29, 1, 1);
	db.InsertQuestionContent_translate(14, "J'ai besoin d'aide pour faire mes activités habituelles", 31, 1, 1);
	db.InsertQuestionContent_translate(15, "Je suis frustré(e) d'être trop fatigué(e) pour pouvoir faire ce que je veux", 32, 1, 1);
	db.InsertQuestionContent_translate(16, "Je dois limiter mes activités sociales parce que je suis fatigué(e)", 33, 1, 1);
	db.InsertQuestionContent_translate(17, "Vous habiller, y compris nouer vos lacets ou fermer vos boutons", 34, 1, 2);
	db.InsertQuestionContent_translate(18, "Vous mettre et vous lever du lit", 35, 1, 2);
	db.InsertQuestionContent_translate(19, "Porter à votre bouche une tasse ou un verre bien plein", 36, 1, 2);
	db.InsertQuestionContent_translate(20, "Marcher à l'extérieur sur terrain plein", 37, 1, 2);
	db.InsertQuestionContent_translate(21, "Vous laver et vous sécher entièrement", 38, 1, 2);
	db.InsertQuestionContent_translate(22, "Vous baisser pour ramasser un vêtement par terre", 39, 1, 2);
	db.InsertQuestionContent_translate(23, "Ouvrir et fermer un robinet", 40, 1, 2);
	db.InsertQuestionContent_translate(24, "Monter et descendre d'une voiture", 41, 1, 2);
	db.InsertQuestionContent_translate(25, "Marcher 3 kilomètres", 42, 1, 2);
	db.InsertQuestionContent_translate(26, "Participer à des activités de plein air ou sportives", 43, 1, 2);
	db.InsertQuestionContent_translate(27, "Quel degré de douleur votre polyarthrite a-t-elle occasionnée la semaine passée ?", 44, 1, -1);
	db.InsertQuestionContent_translate(28, "En prenant en compte toutes les conséquences de votre maladie, comment vous sentez-vous actuellement ? ", 45, 1, -1);
	db.InsertQuestionContent_translate(29, "Niveau de la douleur des doigts gauches", 50, 1, 3);
	db.InsertQuestionContent_translate(30, "Niveau de la douleur des doigts droits", 51, 1, 3);
	db.InsertQuestionContent_translate(32, "Niveau de la douleur de la poignet gauche", 53, 1, 3);
	db.InsertQuestionContent_translate(33, "Niveau de la douleur de la poignet droite", 54, 1, 3);
	db.InsertQuestionContent_translate(34, "Niveau de la douleur de la coude gauche", 56, 1, 3);
	db.InsertQuestionContent_translate(35, "Niveau de la douleur de la coude droite", 57, 1, 3);
	db.InsertQuestionContent_translate(36, "Niveau de la douleur de l'épaule gauche", 58, 1, 3);
	db.InsertQuestionContent_translate(37, "Niveau de la douleur de l'épaule droite", 62, 1, 3);
	db.InsertQuestionContent_translate(38, "Niveau de la douleur des orteils gauches", 63, 1, 3);
	db.InsertQuestionContent_translate(39, "Niveau de la douleur des orteils droits", 64, 1, 3);
	db.InsertQuestionContent_translate(40, "Niveau de la douleur de la cheville gauche", 65, 1, 3);
	db.InsertQuestionContent_translate(41, "Niveau de la douleur de la cheville droite", 67, 1, 3);
	db.InsertQuestionContent_translate(42, "Niveau de la douleur du genoux gauche", 68, 1, 3);
	db.InsertQuestionContent_translate(43, "Niveau de la douleur du genoux droit", 71, 1, 3);
	db.InsertQuestionContent_translate(49, "Niveau de la douleur de la hanche gauche", 72, 1, 3);
	db.InsertQuestionContent_translate(50, "Niveau de la douleur de la hanche droite", 73, 1, 3);
	db.InsertQuestionContent_translate(53, "Vous sentez-vous actuellement en poussée de votre polyarthrite ? ", 74, 1, 4);
	db.InsertQuestionContent_translate(54, "Quel est le degré d'activité de votre polyarthrite ces 6 derniers mois  ?", 75, 1, 23);
	db.InsertQuestionContent_translate(55, "Quel est le degré d'activité de votre polyarthrite aujourd'hui en prenant en compte la douleur et le gonflement des articulations ? ", 76, 1, 23);
	db.InsertQuestionContent_translate(56, "Quel degré de douleurs votre polyarthrite occasionne-t-elle aujourd'hui ?", 77, 1, 23);
	db.InsertQuestionContent_translate(57, "Comment situeriez-vous votre état global de santé, aujourd'hui ?", 78, 1, 23);
	db.InsertQuestionContent_translate(58, "Aviez-vous une raideur des articulations (mains) hier matin au lever ? Si oui, pendant combien de temps ? ", 79, 1, 23);
	db.InsertQuestionContent_translate(59, "Vous habiller, y compris nouer vos lacets et boutonner vos vêtements ?", 81, 1, 2);
	db.InsertQuestionContent_translate(60, "Vous-lavez les cheveux ?", 82, 1, 2);
	db.InsertQuestionContent_translate(61, "Vous-lever d'une chaise ?", 83, 1, 2);
	db.InsertQuestionContent_translate(62, "Vous-mettre au lit et vous lever du lit ?", 85, 1, 2);
	db.InsertQuestionContent_translate(63, "Couper la viande ?", 86, 1, 2);
	db.InsertQuestionContent_translate(64, "Porter à la bouche une tasse ou un verre bien plein ?", 87, 1, 2);
	db.InsertQuestionContent_translate(65, "Ouvrir une brique de lait ou de jus de fruit ?", 88, 1, 2);
	db.InsertQuestionContent_translate(66, "Prendre un bain? Se sécher entièrement?", 89, 1, 2);
	db.InsertQuestionContent_translate(67, "Monter 5 marches ?", 90, 1, 2);
	db.InsertQuestionContent_translate(68, "Vous lavez et vous sécher entièrement ?", 91, 1, 2);
	db.InsertQuestionContent_translate(69, "Prendre un bain ?", 92, 1, 2);
	db.InsertQuestionContent_translate(70, "Vous asseoir et vous relever des toilettes ?", 93, 1, 2);
	db.InsertQuestionContent_translate(71, "Atteindre et prendre un objet pesant 2,5kg situé au-dessus de votre tête ?", 94, 1, 2);
	db.InsertQuestionContent_translate(72, "Vous baisser pour ramasser un vêtement par terre ?", 95, 1, 2);
	db.InsertQuestionContent_translate(73, "Dévisser le couvercle d'un pot déjà ouvert une fois ?", 97, 1, 2);
	db.InsertQuestionContent_translate(74, "Ouvrir et fermer un robinet ?", 98, 1, 2);
	db.InsertQuestionContent_translate(75, "Faire vos courses ?", 99, 1, 2);
	db.InsertQuestionContent_translate(76, "Monter et descendre de votre voiture ?", 100, 1, 2);
	db.InsertQuestionContent_translate(77, "Faire des travaux ménagers tels que pqsser l'aspirateur ou faire du petit jardinage ?", 102, 1, 2);
	db.InsertQuestionContent_translate(81, "Ouvrir une porte de voiture", 96, 1, 2);
	db.InsertQuestionContent_translate(82, "Avez-vous fait un test sanguin cette semaine ?", 103, 1, 4);
	db.InsertQuestionContent_translate(85, "Avez-vous fait des examens radiologiques cette semaine ?", 104, 1, 4);
	db.InsertQuestionContent_translate(86, "Avez-vous pratiqué la physiothérapie cette semaine ?", 105, 1, 4);
	db.InsertQuestionContent_translate(87, "Précisez les tests sanguins que vous avez faits", 107, 1, 7);
	db.InsertQuestionContent_translate(88, "Précisez l'examen radiologique que vous avez fait", 108, 1, 6);
	db.InsertQuestionContent_translate(89, "Avez-vous pris des médicaments sans ordonnance cette semaine ?", 109, 1, 4);
	db.InsertQuestionContent_translate(90, "Précisez les médicaments que vous avez pris sans ordonnace", 110, 1, 5);
	db.InsertQuestionContent_translate(91, "Effets secondaires ressentis cette semaine", 111, 1, 8);
	db.InsertQuestionContent_translate(92, "Quelle est la valeur de votre VS en (mm/h)", 112, 1, 10);
	db.InsertQuestionContent_translate(93, "Doigts droits gonflés", 113, 1, -1);
	db.InsertQuestionContent_translate(94, "Comment évaluez-vous l'activité de votre polyarthrite pendant les dernieres 48 heures ?", 114, 1, -1);
	db.InsertQuestionContent_translate(95, "Doigts gauches gonflés ", 115, 1, 4);
	db.InsertQuestionContent_translate(96, "Doigts droits gonflés", 116, 1, 4);
	db.InsertQuestionContent_translate(97, "Poignet gauche gonflée", 117, 1, 4);
	db.InsertQuestionContent_translate(98, "Poignet droite gonflée", 118, 1, 4);
	db.InsertQuestionContent_translate(99, "Coude gauche gonflée", 119, 1, 4);
	db.InsertQuestionContent_translate(100, "Coude droite gonflée", 120, 1, 4);
	db.InsertQuestionContent_translate(101, "Epaule gauche gonflée", 122, 1, 4);
	db.InsertQuestionContent_translate(102, "Epaule droite gonflée", 123, 1, 4);
	db.InsertQuestionContent_translate(103, "Orteils gauches gonflés", 124, 1, 4);
	db.InsertQuestionContent_translate(104, "Orteils droits gonflés", 125, 1, 4);
	db.InsertQuestionContent_translate(105, "Cheville gauche gonflée", 127, 1, 4);
	db.InsertQuestionContent_translate(106, "Cheville droite gonflée", 128, 1, 4);
	db.InsertQuestionContent_translate(107, "Genoux gauche gonflé", 129, 1, 4);
	db.InsertQuestionContent_translate(108, "Genoux droite gonflée", 130, 1, 4);
	db.InsertQuestionContent_translate(109, "Hanche gauche gonflée", 131, 1, 4);
	db.InsertQuestionContent_translate(110, "Hanche droite gonflée", 132, 1, 4);
	db.InsertQuestionContent_translate(111, "S'habiller et se préparer", 134, 1, 4);
	db.InsertQuestionContent_translate(112, "Utilisez-vous des accessoires pour s'habiller (crochet a bouton, crochet a fermeture éclair, chausse pied a longue ?", 136, 1, 4);
	db.InsertQuestionContent_translate(114, "Utilisez-vous un unstensile spécialement adapté?", 137, 1, 4);
	db.InsertQuestionContent_translate(115, "Manger", 138, 1, 4);
	db.InsertQuestionContent_translate(117, "Vos moyens de contraception ", 142, 1, 13);
	db.InsertQuestionContent_translate(118, "Vous êtes", 143, 1, 14);
	db.InsertQuestionContent_translate(119, "Quels antécédents d'infections avez vous ", 144, 1, 15);
	db.InsertQuestionContent_translate(122, "Avez-vous des antécédents de fracture due a l'ostéoporose", 146, 1, 4);
	db.InsertQuestionContent_translate(123, "Etes-vous vacciné(e) contre la DT-Polio", 147, 1, 4);
	db.InsertQuestionContent_translate(124, "Date du dernier rappel de la DT-Polio", 149, 1, 10);
	db.InsertQuestionContent_translate(125, "Avez-vous fait le vaccin contre la Grippe cette année", 151, 1, 4);
	db.InsertQuestionContent_translate(126, "Date du dernier rappel de la Grippe", 152, 1, 10);
	db.InsertQuestionContent_translate(127, "Etes-vous vacciné(e) contre la Pneumonie", 153, 1, 4);
	db.InsertQuestionContent_translate(128, "Date du dernier rappel de la Pneumonie", 154, 1, 10);
	db.InsertQuestionContent_translate(129, "Profession", 155, 1, 16);
	db.InsertQuestionContent_translate(130, "Adresse", 157, 1, -1);
	db.InsertQuestionContent_translate(131, "Prénom", 158, 1, -1);
	db.InsertQuestionContent_translate(133, "Se lever", 160, 1, 4);
	db.InsertQuestionContent_translate(134, "Avez-vous besoin de l'aide de quelqu'un pour marcher ?", 161, 1, 4);
	db.InsertQuestionContent_translate(135, "Utilisez-vous une canne?", 162, 1, 4);
	db.InsertQuestionContent_translate(137, "Utilisez-vous un déambulateur ?", 164, 1, 4);
	db.InsertQuestionContent_translate(138, "Utilisez-vous des béquilles?", 165, 1, 4);
	db.InsertQuestionContent_translate(139, "Utilisez-vous une chaise roulante?", 166, 1, 4);
	db.InsertQuestionContent_translate(140, "Utilisez-vous besoin de l'aide de quelqu'un pour votre hygiène?", 167, 1, 4);
	db.InsertQuestionContent_translate(141, "Utilisez-vous un siège de WC surlev�?", 168, 1, 4);
	db.InsertQuestionContent_translate(142, "Utilisez-vous un siège de baignoire?", 169, 1, 4);
	db.InsertQuestionContent_translate(143, "Utilisez-vous des poign�es ou une barre de baigoire?", 170, 1, 4);
	db.InsertQuestionContent_translate(144, "Utilisez-vous un instrument � long manche dans la salle de bain?", 171, 1, 4);
	db.InsertQuestionContent_translate(145, "Avez-vous besoin de l'aide de quelqu'un pour atteindre ou attraper un objet?", 173, 1, 4);
	db.InsertQuestionContent_translate(146, "Utilisez-vous un instrument � long manche pour attraper les objets?", 174, 1, 4);
	db.InsertQuestionContent_translate(147, "Avez-vous besoin de l'aide de quelqu'un pour saisir et ouvrir des objets?", 175, 1, 4);
	db.InsertQuestionContent_translate(148, "Utilisez-vous un ouvre pot pour des pots d�j� ouverts?", 176, 1, 4);
	db.InsertQuestionContent_translate(149, "Avez-vous besoin de l'aide de quelqu'un pour faires vos courses et vos t�ches m�nagères?", 177, 1, 4);
	db.InsertQuestionContent_translate(151, "Nom", 178, 1, -1);
	db.InsertQuestionContent_translate(152, "Phone", 179, 1, -1);
	db.InsertQuestionContent_translate(153, "Mobile", 180, 1, -1);
	db.InsertQuestionContent_translate(154, "E-mail", 183, 1, -1);
	db.InsertQuestionContent_translate(155, "Quelle est la valeur de votre CRP en (mg/l)", 113, 1, 10);
	db.InsertQuestionContent_translate(156, "Etes-vous en m�nopause", 184, 1, 4);
	db.InsertQuestionContent_translate(157, "Age de d�but", 185, 1, 10);
	db.InsertQuestionContent_translate(158, "Votre m�decin est", 186, 1, 16);
	db.InsertQuestionContent_translate(159, "Vous avez pris vos m�dicaments exactement comme indiqu� sur votre ordonnance ?", 187, 1, 4);
	db.InsertQuestionContent_translate(160,  "Durant la p�riode o� vous avez pris ces m�dicaments, avez-vous senti:", 188, 1,20);
	db.InsertQuestionContent_translate(161, "Comment �valuez-vous l'activit� de votre polyarthrite pendant les dernieres 48 heures ?", 189, 1, 23);
	db.InsertQuestionContent_translate(162, "En prenant en compte toutes les cons�quences de votre maladie, comment vous sentez-vous actuellement ?", 190, 1, 23);
	db.InsertQuestionContent_translate(163, "Quel degr� de douleur votre polyarthrite a-t-elle occasionn� la semaine pass�e ?", 191, 1, 23);
	db.InsertQuestionContent_translate(164, "Concernant votre polyarthrite, consid�rez-vous votre �tat actuel satisfaisant ?", 192, 1, 24);
	db.InsertQuestionContent_translate(165, "Vous sentez-vous actuellement en pouss�e de votre polyarthrite ?", 193, 1, 24);
	db.InsertQuestionContent_translate(166, "Connaissez-vous votre VS du mois (Vitesse de S�dimentation)?", 194, 1, 24);
	db.InsertQuestionContent_translate(167, "Connaissez-vous votre CRP du mois (Prot�ine C-R�active) ?", 195, 1, 24);
	db.InsertQuestionContent_translate(168, "Votre VS est �gal (mm/h)", 196, 1, 25);
	db.InsertQuestionContent_translate(169, "Votre CRP est �gal (mg/l)", 197, 1, 25);
	db.InsertQuestionContent_translate(170, "Avez-vous besoin de l'aide de quelqu'un pour s'habiller ou se pr�parer ", 198, 1, 2);
	db.InsertQuestionContent_translate(171, "Avez-vous besoin de l'aide de quelqu'un pour manger ?", 199, 1, 2);
	db.InsertQuestionContent_translate(172, "Avez-vous besoin de l'aide de quelqu'un pour se lever?", 200, 1, 2);
	db.InsertQuestionContent_translate(173, "Ouvrir et fermer un robinet ?", 201, 1, 2);
	db.InsertQuestionContent_translate(174, "Vous asseoir et vous relever des toilettes ?", 202, 1, 2);

	db.InsertQuestionContent_translate(175, "Doigt droitD1_1", 204, 1, 1);
	db.InsertQuestionContent_translate(176, "Doigt droitD1_2", 205, 1, 1);
	db.InsertQuestionContent_translate(177, "Doigt droitD2_1", 206, 1, 1);
	db.InsertQuestionContent_translate(178, "Doigt droitD2_2", 207, 1, 1);
	db.InsertQuestionContent_translate(179, "Doigt droitD3_1", 208, 1, 1);
	db.InsertQuestionContent_translate(180, "Doigt droitD3_2", 209, 1, 1);
	db.InsertQuestionContent_translate(181, "Doigt droitD4_1", 210, 1, 1);
	db.InsertQuestionContent_translate(182, "Doigt droitD4_2", 211, 1, 1);
	db.InsertQuestionContent_translate(183, "Doigt droitD5_1", 212, 1, 1);
	db.InsertQuestionContent_translate(184, "Doigt droitD5_2", 213, 1, 1);
	db.InsertQuestionContent_translate(185, "Doigt gaucheD1_1", 214, 1, 1);
	db.InsertQuestionContent_translate(186, "Doigt gaucheD1_2", 215, 1, 1);
	db.InsertQuestionContent_translate(187, "Doigt gaucheD2_1", 216, 1, 1);
	db.InsertQuestionContent_translate(188, "Doigt gaucheD2_2", 217, 1, 1);
	db.InsertQuestionContent_translate(189, "Doigt gaucheD3_1", 218, 1, 1);
	db.InsertQuestionContent_translate(190, "Doigt gaucheD3_2", 219, 1, 1);
	db.InsertQuestionContent_translate(191, "Doigt gaucheD4_1", 220, 1, 1);
	db.InsertQuestionContent_translate(192, "Doigt gaucheD4_2", 221, 1, 1);
	db.InsertQuestionContent_translate(193, "Doigt gaucheD5_1", 222, 1, 1);
	db.InsertQuestionContent_translate(194, "Doigt gaucheD5_2", 223, 1, 1);
	db.InsertQuestionContent_translate(195, "Doigt droitG1_1", 224, 1, 4);
	db.InsertQuestionContent_translate(196, "Doigt droitG1_2", 225, 1, 4);
	db.InsertQuestionContent_translate(197, "Doigt droitG2_1", 226, 1, 4);
	db.InsertQuestionContent_translate(198, "Doigt droitG2_2", 227, 1, 4);
	db.InsertQuestionContent_translate(199, "Doigt droitG3_1", 228, 1, 4);
	db.InsertQuestionContent_translate(200, "Doigt droitG3_2", 229, 1, 4);
	db.InsertQuestionContent_translate(201, "Doigt droitG4_1", 230, 1, 4);
	db.InsertQuestionContent_translate(202, "Doigt droitG4_2", 231, 1, 4);
	db.InsertQuestionContent_translate(203, "Doigt droitG5_1", 232, 1, 4);
	db.InsertQuestionContent_translate(204, "Doigt droitG5_2", 233, 1, 4);
	db.InsertQuestionContent_translate(205, "Doigt gaucheG1_1", 234, 1, 4);
	db.InsertQuestionContent_translate(206, "Doigt gaucheG1_2", 235, 1, 4);
	db.InsertQuestionContent_translate(207, "Doigt gaucheG2_1", 236, 1, 4);
	db.InsertQuestionContent_translate(208, "Doigt gaucheG2_2", 237, 1, 4);
	db.InsertQuestionContent_translate(209, "Doigt gaucheG3_1", 238, 1, 4);
	db.InsertQuestionContent_translate(210, "Doigt gaucheG3_2", 239, 1, 4);
	db.InsertQuestionContent_translate(211, "Doigt gaucheG4_1", 240, 1, 4);
	db.InsertQuestionContent_translate(212, "Doigt gaucheG4_2", 241, 1, 4);
	db.InsertQuestionContent_translate(213, "Doigt gaucheG5_1", 242, 1, 4);
	db.InsertQuestionContent_translate(214, "Doigt gaucheG5_2", 243, 1, 4);
	db.InsertQuestionContent_translate(215, "Quels soins avez-vous eu cette semaine?", 203, 1, 19);
	
	//Filling the table ScoreTypes
	db.InsertScoreTypes(2, "FACIT-Fatigue","FACIT");
	db.InsertScoreTypes(1, "HAQ","HAQ");
	db.InsertScoreTypes(7, "DAS28-VS","DAS28-VS");
	db.InsertScoreTypes(5, "RAPID3","RAPID3");
	db.InsertScoreTypes(6, "RAPID4","RAPID4");
	db.InsertScoreTypes(3, "RADAI5","RADAI5");
	db.InsertScoreTypes(8, "Force de Pr�hension","SENSOR");
	db.InsertScoreTypes(9, "HAD-D�pr�ssion","Depression");
	db.InsertScoreTypes(10, "HAD-Anxi�t�","Anxiety");
	db.InsertScoreTypes(11, "DAS28-CRP","DAS28-CRP");
	//Filling the table QAFamilies 
	db.InsertQAFamilies(1, "HAQ_1", 1);
	db.InsertQAFamilies(2, "HAQ_2", 2);
	db.InsertQAFamilies(3, "HAQ_3", 3);
	db.InsertQAFamilies(4, "HAQ_4", 4);
	db.InsertQAFamilies(5, "HAQ_5", 5);
	db.InsertQAFamilies(6, "HAQ_6", 6);
	db.InsertQAFamilies(7, "HAQ_7", 7);
	db.InsertQAFamilies(8, "HAQ_8", 8);
	db.InsertQAFamilies(9, "RAP3", 9);
	db.InsertQAFamilies(10, "HAQ_RAP3", 10);
	db.InsertQAFamilies(11, "DAS28", 11);
	db.InsertQAFamilies(12, "SKELETON_PAIN", 12);
	db.InsertQAFamilies(13, "SKELETON_SWOLLEN", 13);
	db.InsertQAFamilies(14, "DIVERS", 14);
	db.InsertQAFamilies(15, "HAQ_1_RAP3", 15);
	db.InsertQAFamilies(16, "HAQ_2_RAP3", 16);
	db.InsertQAFamilies(17, "HAQ_3_RAP3", 17);
	db.InsertQAFamilies(18, "HAQ_4_RAP3", 18);
	db.InsertQAFamilies(19, "HAQ_5_RAP3", 19);
	db.InsertQAFamilies(20, "HAQ_6_RAP3", 20);
	db.InsertQAFamilies(21, "HAQ_7_RAP3", 21);
	db.InsertQAFamilies(22, "HAQ_8_RAP3", 22);
	db.InsertQAFamilies(23, "IF", 23);

	//Filling the table QAContents 
	db.InsertQAContents(20, "HI7", 2, 0, 1, -1, 1);
	db.InsertQAContents(21, "HI12", 2, 0, 2, -1, 1);
	db.InsertQAContents(22, "An1", 2, 0, 3, -1, 1);
	db.InsertQAContents(23, "An2", 2, 0, 4, -1, 1);
	db.InsertQAContents(24, "An3", 2, 0, 5, -1, 1);
	db.InsertQAContents(25, "An4", 2, 0, 6, -1, 1);
	db.InsertQAContents(26, "An5", 2, 0, 7, -1, 1);
	db.InsertQAContents(27, "An7", 2, 0, 8, -1, 1);
	db.InsertQAContents(28, "An8", 2, 0, 9, -1, 1);
	db.InsertQAContents(29, "An12", 2, 0, 10, -1, 1);
	db.InsertQAContents(31, "An14", 2, 0, 11, -1, 1);
	db.InsertQAContents(32, "An15", 2, 0, 12, -1, 1);
	db.InsertQAContents(33, "An16", 2, 0, 13, -1, 1);
	db.InsertQAContents(34, "RAP3_1_1", 2, 0, 1, -1, 5);
	db.InsertQAContents(35, "RAP3_1_2", 2, 0, 2, -1, 5);
	db.InsertQAContents(36, "RAP3_1_3", 2, 0, 3, -1, 5);
	db.InsertQAContents(37, "RAP3_1_4", 2, 0, 4, -1, 5);
	db.InsertQAContents(38, "RAP3_1_5", 2, 0, 5, -1, 5);
	db.InsertQAContents(39, "RAP3_1_6", 2, 0, 6, -1, 5);
	db.InsertQAContents(40, "RAP3_1_7", 2, 0, 7, -1, 5);
	db.InsertQAContents(41, "RAP3_1_8", 2, 0, 8, -1, 5);
	db.InsertQAContents(42, "RAP3_1_9", 2, 0, 9, -1, 5);
	db.InsertQAContents(43, "RAP3_1_10", 2, 0, 10, -1, 5);
	db.InsertQAContents(44, "RAP3_2", 2, 6, 11, -1, 5);
	db.InsertQAContents(45, "RAP3_3", 2, 6, 12, -1, 5);
	db.InsertQAContents(50, "JOINT_P_LF", 2, 0, 1, -1, 6);
	db.InsertQAContents(51, "JOINT_P_RF", 2, 0, 2, -1, 6);
	db.InsertQAContents(53, "JOINT_P_LW", 2, 0, 3, -1, 6);
	db.InsertQAContents(54, "JOINT_P_RW", 2, 0, 4, -1, 6);
	db.InsertQAContents(56, "JOINT_P_LE", 2, 0, 5, -1, 6);
	db.InsertQAContents(57, "JOINT_P_RE", 2, 0, 6, -1, 6);
	db.InsertQAContents(58, "JOINT_P_LSh", 2, 0, 7, -1, 6);
	db.InsertQAContents(62, "JOINT_P_RSh", 2, 0, 8, -1, 6);
	db.InsertQAContents(63, "JOINT_P_LT", 2, 0, 9, -1, 6);
	db.InsertQAContents(64, "JOINT_P_RT", 2, 0, 10, -1, 6);
	db.InsertQAContents(65, "JOINT_P_LA", 2, 0, 11, -1, 6);
	db.InsertQAContents(67, "JOINT_P_RA", 2, 0, 12, -1, 6);
	db.InsertQAContents(68, "JOINT_P_LK", 2, 0, 13, -1, 6);
	db.InsertQAContents(71, "JOINT_P_RK", 2, 0, 14, -1, 6);
	db.InsertQAContents(72, "JOINT_P_LH", 2, 0, 15, -1, 6);
	db.InsertQAContents(73, "JOINT_P_RH", 2, 0, 16, -1, 6);
	db.InsertQAContents(74, "RAP4_5", 2, 2, 1, -1, 6);
	db.InsertQAContents(75, "RAD5_1", 2, 6, 1, -1, 7);
	db.InsertQAContents(76, "RAD5_2", 2, 6, 2, -1, 7);
	db.InsertQAContents(77, "RAD5_3", 2, 6, 3, -1, 7);
	db.InsertQAContents(78, "RAD5_4", 2, 6, 4, -1, 7);
	db.InsertQAContents(79, "RAD5_5", 2, 6, 5, -1, 7);
	db.InsertQAContents(81, "HAQ1_1_RAP3", 2, 0, 1, -1, 2);
	db.InsertQAContents(82, "HAQ1_2", 2, 0, 2, -1, 2);
	db.InsertQAContents(83, "HAQ2_1", 2, 0, 1, -1, 2);
	db.InsertQAContents(85, "HAQ2_2_RAP3", 2, 0, 2, -1, 2);
	db.InsertQAContents(86, "HAQ3_1", 2, 0, 1, -1, 2);
	db.InsertQAContents(87, "HAQ3_2_RAP3", 2, 0, 2, -1, 2);
	db.InsertQAContents(88, "HAQ3_3", 2, 0, 3, -1, 2);
	db.InsertQAContents(89, "HAQ4_1_RAP3", 2, 0, 1, -1, 2);
	db.InsertQAContents(90, "HAQ4_2", 2, 0, 2, -1, 2);
	db.InsertQAContents(91, "HAQ5_1_RAP3", 2, 0, 1, -1, 2);
	db.InsertQAContents(92, "HAQ5_2", 2, 0, 2, -1, 2);
	db.InsertQAContents(93, "HAQ5_3", 2, 0, 3, -1, 2);
	db.InsertQAContents(94, "HAQ6_1", 2, 0, 1, -1, 2);
	db.InsertQAContents(95, "HAQ6_2_RAP3", 2, 0, 2, -1, 2);
	db.InsertQAContents(96, "HAQ7_1", 2, 0, 1, -1, 2);
	db.InsertQAContents(97, "HAQ7_2", 2, 0, 2, -1, 2);
	db.InsertQAContents(98, "HAQ7_3_RAP3", 2, 0, 3, -1, 2);
	db.InsertQAContents(99, "HAQ8_1", 2, 0, 1, -1, 2);
	db.InsertQAContents(100, "HAQ8_2_RAP3", 2, 0, 2, -1, 2);
	db.InsertQAContents(102, "HAQ8_3", 2, 0, 3, -1, 2);
	db.InsertQAContents(103, "BT1", 2, 2, 1, 14, -1);
	db.InsertQAContents(104, "XRAY1", 2, 2, 3, 14, -1);
	db.InsertQAContents(105, "PHT", 2, 2, 5, 14, -1);
	db.InsertQAContents(107, "BT2", 2, 1, 2, 14, -1);
	db.InsertQAContents(108, "XRAY2", 2, 1, 4, 14, -1);
	db.InsertQAContents(109, "OC1", 1, 2, 1, -1, -1);
	db.InsertQAContents(110, "OC2", 1, 1, 2, -1, -1);
	db.InsertQAContents(111, "SE", 1, 1, 3, -1, -1);
	db.InsertQAContents(112, "VS", 2, 4, 1, -1, 3);
	db.InsertQAContents(113, "CRP", 2, 4, 2, -1, 3);
	db.InsertQAContents(114, "DAS28_1", 2, 6, 3, -1, 3);
	db.InsertQAContents(115, "JOINT_S_LF", 2, 2, 1, 13, 3);
	db.InsertQAContents(116, "JOINT_S_RF", 2, 2, 2, 13, 3);
	db.InsertQAContents(117, "JOINT_S_LW", 2, 2, 3, 13, 3);
	db.InsertQAContents(118, "JOINT_S_RW", 2, 2, 4, 13, 3);
	db.InsertQAContents(119, "JOINT_S_LE", 2, 2, 5, 13, 3);
	db.InsertQAContents(120, "JOINT_S_RE", 2, 2, 6, 13, 3);
	db.InsertQAContents(122, "JOINT_S_LSh", 2, 2, 7, 13, 3);
	db.InsertQAContents(123, "JOINT_S_RSh", 2, 2, 8, 13, 3);
	db.InsertQAContents(124, "JOINT_S_LT", 2, 2, 9, 13, 3);
	db.InsertQAContents(125, "JOINT_S_RT", 2, 2, 10, 13, 3);
	db.InsertQAContents(127, "JOINT_S_LA", 2, 2, 11, 13, 3);
	db.InsertQAContents(128, "JOINT_S_RA", 2, 2, 12, 13, 3);
	//db.InsertQAContents(0, "JOINT_S_LK", 2, 2, 13, 13, 3);
	db.InsertQAContents(129, "JOINT_S_LK", 2, 2, 13, 13, 3);
	db.InsertQAContents(130, "JOINT_S_RK", 2, 2, 14, 13, 3);
	db.InsertQAContents(131, "JOINT_S_LH", 2, 2, 15, 13, 3);
	db.InsertQAContents(132, "JOINT_S_RH", 2, 2, 16, 13, 3);
	db.InsertQAContents(134, "HAQ1_1_C", 2, 2, 1, -1, 2);
	db.InsertQAContents(136, "HAQ1_2_C", 2, 2, 2, -1, 2);
	db.InsertQAContents(137, "HAQ1_3_C", 2, 2, 3, -1, 2);
	db.InsertQAContents(138, "HAQ3_1_C", 2, 2, 4, -1, 2);
	db.InsertQAContents(142, "IF_C", 0, 1, 1, -1, -1);
	db.InsertQAContents(143, "IF_RF", 0, 1, 2, -1, -1);
	db.InsertQAContents(144, "IF_AI", 0, 1, 3, -1, -1);
	db.InsertQAContents(146, "IF_AF", 0, 2, 4, -1, -1);
	db.InsertQAContents(147, "IF_DT", 0, 2, 5, -1, -1);
	db.InsertQAContents(149, "IF_DT_D", 0, 5, 6, -1, -1);
	db.InsertQAContents(151, "IF_G", 0, 2, 7, -1, -1);
	db.InsertQAContents(152, "IF_G_D", 0, 5, 8, -1, -1);
	db.InsertQAContents(153, "IF_PN", 0, 2, 9, -1, -1);
	db.InsertQAContents(154, "IF_PN_D", 0, 5, 10, -1, -1);
	db.InsertQAContents(155, "IF_DOC_P", 0, 0, 1, -1, -1);
	db.InsertQAContents(157, "IF_DOC_AD", 0, 3, 4, -1, -1);
	db.InsertQAContents(158, "IF_DOC_FN", 0, 3, 2, -1, -1);
	db.InsertQAContents(160, "HAQ2_1_C", 2, 2, 5, -1, -1);
	db.InsertQAContents(161, "HAQ4_1_C", 2, 2, 6, -1, -1);
	db.InsertQAContents(162, "HAQ4_2_C", 2, 2, 7, -1, -1);
	db.InsertQAContents(164, "HAQ4_3_C", 2, 2, 8, -1, -1);
	db.InsertQAContents(165, "HAQ4_4_C", 2, 2, 9, -1, -1);
	db.InsertQAContents(166, "HAQ4_5_C", 2, 2, 10, -1, -1);
	db.InsertQAContents(167, "HAQ5_1_C", 2, 2, 11, -1, -1);
	db.InsertQAContents(168, "HAQ5_2_C", 2, 2, 12, -1, -1);
	db.InsertQAContents(169, "HAQ5_3_C", 2, 2, 13, -1, -1);
	db.InsertQAContents(170, "HAQ5_4_C", 2, 2, 14, -1, -1);
	db.InsertQAContents(171, "HAQ5_5_C", 2, 2, 15, -1, -1);
	db.InsertQAContents(173, "HAQ6_1_C", 2, 2, 16, -1, -1);
	db.InsertQAContents(174, "HAQ6_2_C", 2, 2, 17, -1, -1);
	db.InsertQAContents(175, "HAQ7_1_C", 2, 2, 18, -1, -1);
	db.InsertQAContents(176, "HAQ7_2_C", 2, 2, 19, -1, -1);
	db.InsertQAContents(177, "HAQ8_1_C", 2, 2, 20, -1, -1);
	db.InsertQAContents(178, "IF_DOC_LN", 0, 3, 3, -1, -1);
	db.InsertQAContents(179, "IF_DOC_PH", 0, 3, 5, -1, -1);
	db.InsertQAContents(180, "IF_DOC_MO", 0, 3, 6, -1, -1);
	db.InsertQAContents(183, "IF_DOC_EM", 0, 3, 7, -1, -1);
	db.InsertQAContents(184, "IF_Me", 0, 2, 1, -1, -1);
	db.InsertQAContents(185, "IF_Me_age", 0, 2, 2, -1, -1);
	db.InsertQAContents(187, "M_1", 1, 2, 1, -1, -1);
	db.InsertQAContents(188, "SE", 1, 1, 3, -1, -1);
	db.InsertQAContents(189, "DAS28_1", 2, 6, 3, -1, 3);
	db.InsertQAContents(190, "RAP3_3", 2, 6, 12, -1, 5);
	db.InsertQAContents(191, "RAP3_2", 2, 6, 11, -1, 5);
	db.InsertQAContents(192, "G", 2, 6, 2, -1, 7);
	db.InsertQAContents(193, "RAP4_5", 2, 2, 1, -1, 6);
	db.InsertQAContents(194, "VS_YN", 2, 4, 1, -1, 3);
	db.InsertQAContents(195, "CRP_YN", 2, 4, 2, -1, 3);
	db.InsertQAContents(196, "VS", 2, 4, 1, -1, 3);
	db.InsertQAContents(197, "CRP", 2, 4, 2, -1, 3);
	db.InsertQAContents(198, "HAQ1_1_C", 2, 2, 1, -1, 2);
	db.InsertQAContents(199, "HAQ3_1_C", 2, 2, 4, -1, 2);
	db.InsertQAContents(200, "HAQ2_1_C", 2, 2, 5, -1, -1);
	db.InsertQAContents(201, "HAQ7_3_RAP3", 2, 0, 3, -1, 2);
	db.InsertQAContents(202, "HAQ5_3", 2, 0, 3, -1, 2);
	
	db.InsertQAContents(203, "O_Int", 2, 1, -1, -1, -1);
	
	db.InsertQAContents(204, "JOINT_P_RF1_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(205, "JOINT_P_RF1_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(206, "JOINT_P_RF2_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(207, "JOINT_P_RF2_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(208, "JOINT_P_RF3_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(209, "JOINT_P_RF3_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(210, "JOINT_P_RF4_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(211, "JOINT_P_RF4_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(212, "JOINT_P_RF5_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(213, "JOINT_P_RF5_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(214, "JOINT_P_LF1_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(215, "JOINT_P_LF1_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(216, "JOINT_P_LF2_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(217, "JOINT_P_LF2_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(218, "JOINT_P_LF3_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(219, "JOINT_P_LF3_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(220, "JOINT_P_LF4_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(221, "JOINT_P_LF4_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(222, "JOINT_P_LF5_1", 2, 0, -1, 12, 3);
	db.InsertQAContents(223, "JOINT_P_LF5_2", 2, 0, -1, 12, 3);
	db.InsertQAContents(224, "JOINT_S_RF1_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(225, "JOINT_S_RF1_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(226, "JOINT_S_RF2_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(227, "JOINT_S_RF2_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(228, "JOINT_S_RF3_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(229, "JOINT_S_RF3_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(230, "JOINT_S_RF4_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(231, "JOINT_S_RF4_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(232, "JOINT_S_RF5_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(233, "JOINT_S_RF5_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(234, "JOINT_S_LF1_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(235, "JOINT_S_LF1_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(236, "JOINT_S_LF2_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(237, "JOINT_S_LF2_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(238, "JOINT_S_LF3_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(239, "JOINT_S_LF3_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(240, "JOINT_S_LF4_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(241, "JOINT_S_LF4_2", 2, 2, -1, 13, 3);
	db.InsertQAContents(242, "JOINT_S_LF5_1", 2, 2, -1, 13, 3);
	db.InsertQAContents(243, "JOINT_S_LF5_2", 2, 2, -1, 13, 3);
	
	//Filling the table DrugFreqOrDoses
	db.InsertDrugFreqOrDoses(1, 1, "Une fois par jour", 1);
	db.InsertDrugFreqOrDoses(2, 0, "10 mg", 1);
	db.InsertDrugFreqOrDoses(3, 0, "20 mg", 1);
	db.InsertDrugFreqOrDoses(4, 1, "Une fois par jour", 2);
	db.InsertDrugFreqOrDoses(5, 1, "Une fois par semaine", 3);
	db.InsertDrugFreqOrDoses(6, 1, "Une fois par jour", 4);
	db.InsertDrugFreqOrDoses(7, 0, "200 mg", 4);
	db.InsertDrugFreqOrDoses(8, 0, "400 mg", 4);
	db.InsertDrugFreqOrDoses(9, 1, "Un comprim� par jour", 5);
	db.InsertDrugFreqOrDoses(10, 0, "2 g", 5);
	db.InsertDrugFreqOrDoses(11, 1, "Une fois tous les 15 jours", 8);
	db.InsertDrugFreqOrDoses(12, 0, "200 mg", 8);
	db.InsertDrugFreqOrDoses(13, 1, "Une fois par semaine", 9);
	db.InsertDrugFreqOrDoses(14, 1, "Deux fois par semaine", 9);
	db.InsertDrugFreqOrDoses(15, 0, "50 mg", 9);
	db.InsertDrugFreqOrDoses(16, 0, "25 mg", 9);
	db.InsertDrugFreqOrDoses(17, 1, "Une fois tous les 10 jours", 10);
	db.InsertDrugFreqOrDoses(18, 1, "Une fois tous les 15 jours ", 10);
	db.InsertDrugFreqOrDoses(19, 1, "Une fois tous les 30 jours", 10);
	db.InsertDrugFreqOrDoses(20, 0, "40 mg", 10);
	db.InsertDrugFreqOrDoses(21, 1, "Une fois par jour", 11);
	db.InsertDrugFreqOrDoses(22, 0, "150 mg", 11);
	db.InsertDrugFreqOrDoses(23, 1, "Une fois par jour ", 12);
	db.InsertDrugFreqOrDoses(24, 0, "100 mg", 12);
	db.InsertDrugFreqOrDoses(25, 1, "Une fois par 6 mois", 13);
	db.InsertDrugFreqOrDoses(26, 0, "1000 mg", 13);
	db.InsertDrugFreqOrDoses(27, 1, "Une fois par mois", 14);
	db.InsertDrugFreqOrDoses(28, 0, "500 mg", 14);
	db.InsertDrugFreqOrDoses(29, 0, "750 mg", 14);
	db.InsertDrugFreqOrDoses(30, 0, "1 g", 14);
	db.InsertDrugFreqOrDoses(31, 1, "1 perfusion toutes les 6 semaines", 17);
	db.InsertDrugFreqOrDoses(34, 1, "Une fois par mois", 15);
	db.InsertDrugFreqOrDoses(36, 1, "Une fois par mois", 16);
	db.InsertDrugFreqOrDoses(37, 0, "50 mg", 16);
	db.InsertDrugFreqOrDoses(38, 1, "Une fois par jour", 18);
	db.InsertDrugFreqOrDoses(39, 1, "Deux fois par jour", 18);
	db.InsertDrugFreqOrDoses(40, 0, "250 mg", 18);
	db.InsertDrugFreqOrDoses(41, 0, "275 mg", 18);
	db.InsertDrugFreqOrDoses(42, 0, "500 mg", 18);
	db.InsertDrugFreqOrDoses(43, 0, "550 mg", 18);
	db.InsertDrugFreqOrDoses(44, 0, "750 mg", 18);
	db.InsertDrugFreqOrDoses(45, 1, "Une fois par jour", 20);
	db.InsertDrugFreqOrDoses(46, 0, "30 mg", 20);
	db.InsertDrugFreqOrDoses(47, 0, "60 mg", 20);
	db.InsertDrugFreqOrDoses(48, 4, "Une fois par jour", 21);
	db.InsertDrugFreqOrDoses(49, 1, "Deux fois par jour", 21);
	db.InsertDrugFreqOrDoses(50, 0, "100 mg", 21);
	db.InsertDrugFreqOrDoses(51, 1, "Une fois par jour", 22);
	db.InsertDrugFreqOrDoses(52, 1, "Deux fois par jour", 22);
	db.InsertDrugFreqOrDoses(53, 1, "Trois fois par jour", 22);
	db.InsertDrugFreqOrDoses(54, 0, "50 mg", 22);
	db.InsertDrugFreqOrDoses(55, 0, "100 mg", 22);
	db.InsertDrugFreqOrDoses(56, 0, "200 mg", 22);
	db.InsertDrugFreqOrDoses(57, 1, "Une ampoule par jour", 39);
	db.InsertDrugFreqOrDoses(58, 1, "Deux ampoules par jour", 39);
	db.InsertDrugFreqOrDoses(59, 1, "Trois ampoules par jour", 39);
	db.InsertDrugFreqOrDoses(60, 1, "Quatre ampoules par jour", 39);
	db.InsertDrugFreqOrDoses(61, 1, "Cinq ampoules par jour", 39);
	db.InsertDrugFreqOrDoses(62, 1, "Six ampoules par jour", 39);
	db.InsertDrugFreqOrDoses(63, 1, "Deux fois par jour", 40);
	db.InsertDrugFreqOrDoses(65, 1, "Trois fois par jour", 40);
	db.InsertDrugFreqOrDoses(66, 1, "Une fois par jour", 41);
	db.InsertDrugFreqOrDoses(67, 1, "Deux fois par jour", 41);
	db.InsertDrugFreqOrDoses(68, 1, "Quatre fois par jour", 41);
	db.InsertDrugFreqOrDoses(69, 1, "Une fois par jour", 42);
	db.InsertDrugFreqOrDoses(70, 1, "Deux fois par jour", 42);
	db.InsertDrugFreqOrDoses(71, 1, "Trois fois par jour", 42);
	db.InsertDrugFreqOrDoses(72, 1, "Quatre fois par jour", 42);
	db.InsertDrugFreqOrDoses(77, 1, "Une fois par jour", 44);
	db.InsertDrugFreqOrDoses(78, 1, "Deux fois par jour", 44);
	db.InsertDrugFreqOrDoses(79, 1, "Trois fois par jour", 44);
	db.InsertDrugFreqOrDoses(80, 1, "Un comprim� par jour", 45);
	db.InsertDrugFreqOrDoses(81, 1, "Deux comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(82, 1, "Trois comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(83, 1, "Quatre comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(85, 1, "Cinq comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(86, 1, "Six comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(87, 1, "Sept comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(88, 1, "Huit comprim�s par jour", 45);
	db.InsertDrugFreqOrDoses(92, 1, "Une fois par jour", 47);
	db.InsertDrugFreqOrDoses(93, 1, "Deux fois par jour", 47);
	db.InsertDrugFreqOrDoses(94, 1, "Trois fois par jour", 47);
	db.InsertDrugFreqOrDoses(107, 1, "Une fois par jour", 24);
	db.InsertDrugFreqOrDoses(108, 1, "Deux fois par jour", 24);
	db.InsertDrugFreqOrDoses(109, 0, "100 mg", 24);
	db.InsertDrugFreqOrDoses(110, 0, "200 mg", 24);
	db.InsertDrugFreqOrDoses(111, 1, "Une fois par jour", 25);
	db.InsertDrugFreqOrDoses(112, 1, "Deux fois par jour", 25);
	db.InsertDrugFreqOrDoses(113, 0, "10 mg", 25);
	db.InsertDrugFreqOrDoses(114, 0, "20 mg ", 25);
	db.InsertDrugFreqOrDoses(115, 1, "Une fois par jour", 26);
	db.InsertDrugFreqOrDoses(116, 1, "Deux fois par jour", 26);
	db.InsertDrugFreqOrDoses(117, 1, "Trois fois par jour", 26);
	db.InsertDrugFreqOrDoses(118, 0, "25 mg", 26);
	db.InsertDrugFreqOrDoses(119, 0, "50 mg", 26);
	db.InsertDrugFreqOrDoses(120, 0, "75 mg", 26);
	db.InsertDrugFreqOrDoses(121, 0, "100 mg", 26);
	db.InsertDrugFreqOrDoses(122, 1, "Une fois par jour", 27);
	db.InsertDrugFreqOrDoses(123, 1, "Deux fois par jour", 27);
	db.InsertDrugFreqOrDoses(124, 1, "Trois fois par jour", 27);
	db.InsertDrugFreqOrDoses(125, 0, "25 mg", 27);
	db.InsertDrugFreqOrDoses(126, 1, "Une fois par jour", 28);
	db.InsertDrugFreqOrDoses(127, 1, "Deux fois par jour", 28);
	db.InsertDrugFreqOrDoses(128, 1, "Trois fois par jour", 28);
	db.InsertDrugFreqOrDoses(129, 0, "75 mg", 28);
	db.InsertDrugFreqOrDoses(130, 1, "Une fois par jour", 29);
	db.InsertDrugFreqOrDoses(131, 1, "Deux fois par jour", 29);
	db.InsertDrugFreqOrDoses(132, 0, "100 mg", 29);
	db.InsertDrugFreqOrDoses(133, 0, "200 mg", 29);
	db.InsertDrugFreqOrDoses(134, 1, "Une fois par jour", 30);
	db.InsertDrugFreqOrDoses(135, 1, "Deux fois par jour", 30);
	db.InsertDrugFreqOrDoses(137, 1, "Trois fois par jour", 30);
	db.InsertDrugFreqOrDoses(138, 1, "Une fois par jour", 31);
	db.InsertDrugFreqOrDoses(139, 1, "Deux fois par jour", 31);
	db.InsertDrugFreqOrDoses(141, 0, "7.5 mg", 31);
	db.InsertDrugFreqOrDoses(142, 0, "15 mg", 31);
	db.InsertDrugFreqOrDoses(143, 1, "Une fois par jour", 32);
	db.InsertDrugFreqOrDoses(144, 1, "Deux fois par jour", 32);
	db.InsertDrugFreqOrDoses(145, 0, "100 mg", 32);
	db.InsertDrugFreqOrDoses(146, 1, "Une fois par jour", 33);
	db.InsertDrugFreqOrDoses(147, 1, "Deux fois par jour", 33);
	db.InsertDrugFreqOrDoses(148,1, "Trois fois par jour", 33);
	db.InsertDrugFreqOrDoses(149, 0, "200 mg", 33);
	db.InsertDrugFreqOrDoses(150, 0, "400 mg", 33);
	db.InsertDrugFreqOrDoses(151, 1, "Une fois par jour", 52);
	db.InsertDrugFreqOrDoses(152, 1, "Deux fois par jour", 52);
	db.InsertDrugFreqOrDoses(153, 0, "100 mg", 52);
	db.InsertDrugFreqOrDoses(154, 0, "500 mg", 42);
	db.InsertDrugFreqOrDoses(155, 0, "1 g", 42);
	db.InsertDrugFreqOrDoses(156, 0, "500 mg", 44);
	db.InsertDrugFreqOrDoses(157, 0, "1 g", 44);
	db.InsertDrugFreqOrDoses(158, 1, "Une fois par jour", 40);
	db.InsertDrugFreqOrDoses(159, 1, "Quatre fois par jour", 40);
	db.InsertDrugFreqOrDoses(160, 0, "50 mg", 40);
	db.InsertDrugFreqOrDoses(161, 0, "100 mg", 40);
	db.InsertDrugFreqOrDoses(162, 0, "150 mg", 40);
	db.InsertDrugFreqOrDoses(163, 0, "200 mg", 40);
	db.InsertDrugFreqOrDoses(164, 1, "Quatre fois par jour", 41);
	db.InsertDrugFreqOrDoses(165, 0, "500 mg", 41);
	db.InsertDrugFreqOrDoses(166, 0, "1 g", 41);
	db.InsertDrugFreqOrDoses(167, 1, "Deux comprim�s par jour", 5);
	db.InsertDrugFreqOrDoses(168, 1, "Trois comprim�s par jour", 5);
	db.InsertDrugFreqOrDoses(169, 1, "Quatre comprim�s pas jour", 5);
	db.InsertDrugFreqOrDoses(170, 1, "Cinq comprim�s par jour ", 5);
	db.InsertDrugFreqOrDoses(171, 1, "Six comprim�s par jour", 5);
	db.InsertDrugFreqOrDoses(172, 0, "500 mg", 5);
	db.InsertDrugFreqOrDoses(173, 1, "Deux fois par jour", 4);
	db.InsertDrugFreqOrDoses(174, 0, "7.5 mg", 3);
	db.InsertDrugFreqOrDoses(175, 0, "15 mg", 3);
	db.InsertDrugFreqOrDoses(176, 0, "25 mg", 3);
	db.InsertDrugFreqOrDoses(177, 1, "1 perfusion toutes les 2 mois", 17);
	//Filling the table DrugType
	db.InsertDrugType(1, "BIO", 1);
	db.InsertDrugType(2, "DMARD", 2);
	db.InsertDrugType(3, "ANTI-IN", 3);
	db.InsertDrugType(4, "OC", 4);
	db.InsertDrugType(5, "ANTAL", 5);
	//Filling the table Language
	db.InsertLanguage(1, "French");
	db.InsertLanguage(2, "English");

	//Filling the table Choice
	db.insertChoice(1, 1, "Jamais", 0);
	db.insertChoice(2, 1, "De temps en temps", 1);
	db.insertChoice(3, 1, "Souvent", 2);
	db.insertChoice(4, 1, "La plupart du temps",3);
	db.insertChoice(5, 2, "Pas du tout", 0);
	db.insertChoice(6, 2, "Un peu mais cela ne m'inqui�te pas", 1);
	db.insertChoice(7, 2, "Oui, mais ce n'est pas trop grave", 2);
	db.insertChoice(8, 2, "Oui, tr�s nettement", 3);
	db.insertChoice(9, 3, "Tr�s occasionnellement", 0);
	db.insertChoice(10, 3, "Occasionnellement", 1);
	db.insertChoice(11, 3, "Assez souvent", 2);
	db.insertChoice(12, 3, "Tr�s souvent", 3);
	db.insertChoice(13, 4, "Oui, quoi qu'il arrive", 0);
	db.insertChoice(14, 4, "Oui, en g�n�ral", 1);
	db.insertChoice(15, 4, "Rarement", 2);
	db.insertChoice(16, 4, "Jamais", 3);
	db.insertChoice(17, 5, "Jamais", 0);
	db.insertChoice(18, 5, "Parfois", 1);
	db.insertChoice(19, 5, "Assez souvent", 2);
	db.insertChoice(20, 5, "Tr�s souvent", 3);
	db.insertChoice(21, 6, "Pas du tout", 0);
	db.insertChoice(22, 6, "Pas tellement", 1);
	db.insertChoice(23, 6, "Un peu", 2);
	db.insertChoice(24, 6, "Oui, c'est tout � fait le cas", 3);
	db.insertChoice(25, 7, "Jamais", 0);
	db.insertChoice(26,7, "Pas tr�s souvent", 1);
	db.insertChoice(27, 7, "Assez souvent", 2);
	db.insertChoice(28, 7, "Vraiment tr�s souvent", 3);
	db.insertChoice(29, 8, "Oui, tout autant", 0);
	db.insertChoice(30, 8, "Pas autant", 1);
	db.insertChoice(31, 8, "Un peu seulement", 2);
	db.insertChoice(32, 8, "Presque plus", 3);
	db.insertChoice(33, 9, "Autant que par le pass�", 0);
	db.insertChoice(34, 9, "Plus autant qu'avant", 1);
	db.insertChoice(35, 9, "Vraiment moins qu'avant", 2);
	db.insertChoice(36, 9, "Plus du tout", 3);
	db.insertChoice(37, 10, "La plupart du temps", 0);
	db.insertChoice(38, 10, "Assez souvent", 1);
	db.insertChoice(39, 10, "Rarement", 2);
	db.insertChoice(40, 10, "Jamais", 3);
	db.insertChoice(41, 11, "Jamais", 0);
	db.insertChoice(42, 11, "Parfois", 1);
	db.insertChoice(43,11, "Tr�s souvent", 2);
	db.insertChoice(44, 11, "Presque toujours", 3);
	db.insertChoice(45, 12, "J'y pr�te autant d'attention que par le pass�", 0);
	db.insertChoice(46, 12, "Il se peut que je n'y fasse plus autant attention", 1);
	db.insertChoice(47, 12, "Je n'y accorde pas autant d'attention que je devrais", 2);
	db.insertChoice(48, 12, "Plus du tout", 3);
	db.insertChoice(49, 13, "Autant qu'avant", 0);
	db.insertChoice(50, 13, "Un peu moins qu'avant", 1);
	db.insertChoice(51, 13, "Bien moins qu'avant", 2);
	db.insertChoice(52, 13, "Presque jamais", 3);
	db.insertChoice(53, 14, "Souvent", 0);
	db.insertChoice(54, 14, "Parfois", 1);
	db.insertChoice(55, 14, "Rarement", 2);
	db.insertChoice(56, 14, "Tr�s rarement", 3);

	//Filling the table Decision
	db.insertDecision(1, 1, "anxiety", 0, 7, "Etat anxieux normal");
	db.insertDecision(2, 1, "anxiety", 8, 10, "Etat anxieux douteux");
	db.insertDecision(3, 1, "anxiety", 11, 21, "Etat anxieux certain");
	db.insertDecision(4, 1, "depression", 0, 7, "Etat d�pressif normal");
	db.insertDecision(5, 1, "depression", 8, 10, "Etat d�pressif douteux");
	db.insertDecision(6, 1, "depression", 11, 21, "Etat d�pressif certain");
	//Filling the table Questions
	db.insertQuestion(1, 1, "Je me sens tendu ou �nerv�", "anxiety");
	db.insertQuestion(2, 1, "J'ai une sensation de peur comme si quelque chose d'horrible allait m'arriver", "anxiety");
	db.insertQuestion(3, 1, "Je me fais du souci", "anxiety");
	db.insertQuestion(4, 1, "Je peux rester tranquillement assis � ne rien faire et me sentir d�contract�", "anxiety");
	db.insertQuestion(5, 1, "J'�prouve des sensations de peur et j'ai l'estomac nou�", "anxiety");
	db.insertQuestion(6, 1, "J'ai la bougeotte et n'arrive pas � tenir en place", "anxiety");
	db.insertQuestion(7, 1, "J'�prouve des sensations soudaines de panique", "anxiety");
	db.insertQuestion(8, 1, "Je prends plaisir aux m�mes choses qu'autrefois", "depression");
	db.insertQuestion(9, 1, "Je ris facilement et vois le bon c�t� des choses", "depression");
	db.insertQuestion(10, 1, "Je suis de bonne humeur", "depression");
	db.insertQuestion(11, 1, "J'ai l'impression de fonctionner au ralenti", "depression");
	db.insertQuestion(12, 1, "Je me m'int�resse plus � mon apparence", "depression");
	db.insertQuestion(13, 1, "Je me r�jouis d'avance � l'id�e de faire certaines choses", "depression");
	db.insertQuestion(14, 1, "Je peux prendre plaisir � un bon livre ou � une bonne �mission radio ou t�l�vision", "depression");
	//Filling the table Scales
	db.insertScale(1, "HAD", "2013-01-13");

	

	/******************************SPA*******************************/
	
	/** insert QAFamilies for BASDAI / BASFI */
	db.InsertQAFamilies(30, "BASDAI", 30);
	db.InsertQAFamilies(31, "BASFI", 31);

	
	/** insert QuestionContent_translate for BASDAI and BASFI */


	// BASDAI Insert

	db.InsertQuestionContent_translate(300, "Où situeriez-vous votre degré global de fatigue?", 250, 1, 1);
	db.InsertQuestionContent_translate(301, "Où situeriez-vous votre degré global de douleur au niveau du cou, du dos et des hanches dans le cadre de votre spondylarthrite ankylosante ?", 251, 1, 1);
	db.InsertQuestionContent_translate(302, " Où situeriez-vous votre degré global de douleur/ gonflement articulaire en dehors du cou, du dos et des hanches ?", 252, 1, 1);
	db.InsertQuestionContent_translate(303, "Où situeriez-vous votre degré global de gêne pour les zones sensibles au toucher ou la pression ?", 253, 1, 1);
	db.InsertQuestionContent_translate(304, "Où situeriez-vous votre degré global de raideur matinale depuis votre rêveil ?", 254, 1, 1);
	db.InsertQuestionContent_translate(305, "Quelle est la durée de votre raideur matinale à partir de votre réveil ?", 255, 1, 1);

	// BASFI Insert
	db.InsertQuestionContent_translate(310, "Pouvez-vous mettre vos chaussettes ou collants sans l'aide de quelqu'un ou de tout autre moyen extérieur (ex. : petit appareil vous aidant à mettre les chaussettes) ?", 260, 1, 1);
	db.InsertQuestionContent_translate(311, "Pouvez-vous vous pencher en avant pour ramasser un stylo posé sur le sol sans l'aide d'un moyen extérieur ?", 261, 1, 1);
	db.InsertQuestionContent_translate(312, "Pouvez-vous atteindre une étagère élevée sans l'aide de quelqu'un ou d'un moyen extérieur ?", 262, 1, 1);
	db.InsertQuestionContent_translate(313, "Pouvez-vous vous lever d'une chaise sans accoudoir sans utiliser vos mains ou toute autre aide ?", 263, 1, 1);
	db.InsertQuestionContent_translate(314, "Pouvez-vous vous relever de la position  <<couché sur le dos>>, sans aide ?", 264, 1, 1);
	db.InsertQuestionContent_translate(315, "Pouvez-vous rester debout sans soutien pendant 10 minutes sans ressentir de gêne ?", 265, 1, 1);
	db.InsertQuestionContent_translate(316, "Pouvez-vous monter 12 à 15 marches, en ne posant qu'un pied sur chaque marche, sans vous tenir à la rampe ou utiliser tout autre soutien ?", 266, 1, 1);
	db.InsertQuestionContent_translate(317, "Pouvez-vous regarder par-dessus votre épaule sans vous retourner ?", 267, 1, 1);
	db.InsertQuestionContent_translate(318, "Pouvez-vous effectuer des activités nécessitant un effort physique (ex: mouvements de kinésithérapie, jardinage ou sports) ?", 268, 1, 1);
	db.InsertQuestionContent_translate(319, " Pouvez-vous avoir des activités toute la journée, que ce soit au domicile ou au travail ?", 269, 1, 1);

	/** insert QAContents for BASDAI and BASFI */
	//BASDAI Inserts
	db.InsertQAContents(250, "BASDAI1", 2, 0, 1, 30, 1);
	db.InsertQAContents(251, "BASDAI2", 2, 0, 2, 30, 1);
	db.InsertQAContents(252, "BASDAI3", 2, 0, 3, 30, 1);
	db.InsertQAContents(253, "BASDAI4", 2, 0, 4, 30, 1);
	db.InsertQAContents(254, "BASDAI5", 2, 0, 5, 30, 1);
	db.InsertQAContents(255, "BASDAI6", 2, 0, 6, 30, 1);

	// BASFI Insert
	db.InsertQAContents(260, "BASFI1", 2, 0, 1, 31, 1);
	db.InsertQAContents(261, "BASFI2", 2, 0, 2, 31, 1);
	db.InsertQAContents(262, "BASFI3",2, 0, 3, 31, 1);
	db.InsertQAContents(263, "BASFI4", 2, 0, 4, 31, 1);
	db.InsertQAContents(264, "BASFI5", 2, 0, 5, 31, 1);
	db.InsertQAContents(265, "BASFI6", 2, 0, 6, 31, 1);
	db.InsertQAContents(266, "BASFI7", 2, 0, 7, 31, 1);
	db.InsertQAContents(267, "BASFI8", 2, 0, 8, 31, 1);
	db.InsertQAContents(268, "BASFI9", 2, 0, 9, 31, 1);
	db.InsertQAContents(269, "BASFI10", 2, 0,10, 31, 1);

}}
